const icons = {
  'chevron-arrow-down': require('./chevron-arrow-down').default,
  'chevron-arrow-up': require('./chevron-arrow-up').default,
  'music-note': require('./music-note').default,
  'heart': require('./heart').default,
  'download': require('./download').default,
  'share': require('./share').default,
  'playlist-add': require('./playlist-add').default,
  'step-forward': require('./step-forward').default,
  'step-backward': require('./step-backward').default,
  'play': require('./play').default,
  'pause': require('./pause').default,
  'search': require('./search').default,
  'globe': require('./globe').default,
  'remove': require('./remove').default,
  'checked': require('./checked').default,
  'dot': require('./dot').default,
  'volume': require('./volume').default,
  'shuffle': require('./shuffle').default,
  'loop': require('./loop').default,
  'headphones': require('./headphones').default,
  'verified': require('./verified').default,
  'youtube': require('./youtube').default,
  'close': require('./close').default,
  'bars': require('./bars').default,

  //FA
  'home': require('./home').default,
  'video': require('./video').default,
  'bell': require('./bell').default,
  'angle-down': require('./angle-down').default,
  'analytics': require('./analytics').default,
  'ellipsis-h': require('./ellipsis-h').default,
  'sync-alt': require('./sync-alt').default,
  'play-circle': require('./play-circle').default,
  'list': require('./list').default,
  'repeat': require('./repeat').default,
  'share-square': require('./share-square').default,
  'random': require('./player/random').default,
  'list-alt': require('./player/list-alt').default,
  'repeat-1-alt': require('./player/repeat-1-alt').default,
  'repeat-alt': require('./player/repeat-alt').default,
};

export default icons;
